
########################################################################################################################
#
#       Application Config
#
########################################################################################################################
server:
  port: 15002
  servlet:
    context-path: /exchange-api/
  tomcat:
    access-log-enabled: false
    max-threads: 150

  ######################################################################################################################
  #
  #       Spring Config
  #
  ######################################################################################################################
spring:
  datasource:
    #主数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://39.104.136.10:5432/exchange
    username: exchange
    password: 123456
    druid:
      max-active: 200
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  redis:
    host: 39.104.136.10
    port: 6379
    password:
    timeout: 100000  # 连接超时时长（毫秒）
    jedis:
      pool:
        # 连接池最大连接数(负数表示没有限制) 默认 8
        max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
          # 连接池中的最大空闲连接 默认 8
        max-idle: 8
          # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  ######################################################################################################################
  #
  #       Mybatis Config
  #
  ######################################################################################################################
mybatis:
  type-aliases-package: com.slabs.mapper
  mapper-locations: classpath:mapper/*.xml, mapper/ext/*.xml, mapper/back/*.xml, mapper/fore/*.xml
#  configuration:
#    map-underscore-to-camel-case: true


  ######################################################################################################################
  #
  #       Log Config
  #
  ######################################################################################################################
logging:
  path: logs
  level.com.slabs.mapper: debug

