
server:
  port: 3801
  servlet:
    context-path: /amf-log/



spring:
  datasource:
    #主数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://rm-bp14153abdq6h8329o.mysql.rds.aliyuncs.com/amflog?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
    username: amf-log
    password: amf777
    druid:
      max-active: 50


  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


mybatis:
  type-aliases-package: com.slabs.api.mapper
  mapper-locations: classpath:mapper/*.xml, mapper/ext/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  path: logs
#  level.com.slabs.api.mapper: debug